
/*
- 1
*/
SELECT IDPRODUTO, NOME, SITUACAO FROM PRODUTO
WHERE IDPRODUTO NOT IN (
  SELECT IDPRODUTO FROM PEDIDOITEM itPed
  INNER JOIN PEDIDO ped ON ped.IDPEDIDO = itPed.IDPEDIDO
  WHERE ped.DATAPEDIDO >= ADD_MONTHS(trunc(SysDate), -4));
  
/*
- 2
*/  
UPDATE PRODUTO SET SITUACAO = 'I'
  WHERE IDPRODUTO NOT IN (
  SELECT IDPRODUTO FROM PEDIDOITEM itPed
  INNER JOIN PEDIDO ped ON ped.IDPEDIDO = itPed.IDPEDIDO
  WHERE ped.DATAPEDIDO >= ADD_MONTHS(trunc(SysDate), -4));

/* LEMBRAR: 
IN E EXISTS
IN SEM WHERE, EXISTS COM WHERE*/
/*
- 3
*/
SELECT COUNT (itPed.IDPEDIDOITEM) FROM PEDIDOITEM itPed
JOIN PEDIDO ped ON ped.IDPEDIDO = itPEd.IDPEDIDO 
  WHERE itPed.IDPRODUTO = :produtoID
  AND ped.DATAPEDIDO > trunc(sysdate,'yyyy');