
/*
- 1
*/
SELECT IDPRODUTO, NOME FROM PRODUTO
WHERE IDPRODUTO NOT IN (
  SELECT IDPRODUTO FROM PEDIDOITEM itPed
  INNER JOIN PEDIDO ped ON ped.IDPEDIDO = itPed.IDPEDIDO
  WHERE ped.DATAPEDIDO >= ADD_MONTHS(SysDate, -4));
  
/*
- 2
*/  
UPDATE PRODUTO SET SITUACAO = 'I'
  WHERE IDPRODUTO NOT IN (
  SELECT IDPRODUTO FROM PEDIDOITEM itPed
  INNER JOIN PEDIDO ped ON ped.IDPEDIDO = itPed.IDPEDIDO
  WHERE ped.DATAPEDIDO >= ADD_MONTHS(SysDate, -4));

/*
- 3
*/
SELECT COUNT (itPed.IDPEDIDOITEM) FROM PEDIDOITEM itPed
JOIN PEDIDO ped ON ped.IDPEDIDO = itPEd.IDPEDIDO 
  WHERE itPed.IDPRODUTO = :produtoID
  AND ped.DATAPEDIDO > TO_DATE('2017/01/01','yyyy/mm/dd');